### ISSUE TITLE
embedTweet.php throws exception

### ISSUE THREAD

**Issue by codingmatty** [rainlab/twitter-plugin#2]
Undefined property: stdClass::$html

```
protected function loadTweetContent()
{
    $json = json_decode(Http::get('https://api.twitter.com/1/statuses/oembed.json', function($http){
        $http->data($this->getProperties());
    })->body);

    return $json->html;
}
```

}

**Comment by cilsilver** [comment]
Same has me, having same problem for over 4hours.

protected function loadTweetContent()
    {
        $json = json_decode(Http::get('https://api.twitter.com/1/statuses/oembed.json', function($http){
            $http->data($this->getProperties());
        })->body);

```
    return $json->html;
}
```

}

**Comment by daftspunk** [comment]
This might occur when Twitter's API is down, we should add some exception handling to grab it.

**Comment by bnordland** [comment]
This also uses Twitter API Version 1 which is no longer supported:
[https://api.twitter.com/1/statuses/](https://api.twitter.com/1/statuses/) returns: The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.

Rather than a Tweet ID, it now takes a tweet URL: https://www.hitchhq.com/twitter/activities/get-statusesoembed-575981a88e2e411000b8e5d4

Updated documentation: https://dev.twitter.com/rest/reference/get/statuses/oembed
Example: ttps://publish.twitter.com/oembed?url=https%3A%2F%2Ftwitter.com%2FInterior%2Fstatus%2F507185938620219395

I would recommend switching over to the new API at the same time as adding extra error handling.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
